POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "krist@gmail.com",
    "password":"1234"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "krist@gmail.com",
    "password":"1234"
}
###
GET  http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjRjMmRmN2ZiZTg5MmU4NjZkOTE1ZjQiLCJpYXQiOjE2NDkxNTk3MzgsImV4cCI6MTY0OTI0NjEzOH0.An7bGF0ZxIUuRq1QhEZTbYuCUOYJXX4DFKRjV4EJepg
###
PUT   http://localhost:3000/api/sauces/624c2bf9fbe892e866d915f1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjRjMmRmN2ZiZTg5MmU4NjZkOTE1ZjQiLCJpYXQiOjE2NDkxNTk3MzgsImV4cCI6MTY0OTI0NjEzOH0.An7bGF0ZxIUuRq1QhEZTbYuCUOYJXX4DFKRjV4EJepg
Content-Type: application/json

{
    "name":"pou",
    "likes":1000


}